# Generated by Django 3.1.5 on 2021-01-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelInterface', '0002_auto_20210109_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Prediction',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
