# Generated by Django 3.1.5 on 2021-01-09 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelInterface', '0005_auto_20210109_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
