# Generated by Django 3.1.5 on 2021-01-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelInterface', '0007_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
